# Generated by Django 4.0.4 on 2022-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('courseNumber', models.CharField(blank=True, default='', max_length=20)),
                ('Instructor', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
