# Generated by Django 4.0.4 on 2022-05-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNumber',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
