# Generated by Django 4.0.4 on 2022-05-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
