# Generated by Django 4.0.4 on 2022-05-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('withdrawal', 'withdrawal'), ('desposit', 'deposit')], max_length=15),
        ),
    ]
